###### 겨리 - 2020/12/22
### **가우스-조르당 소거법(Gauss-Jordan Elimination)**
#### 연립방정식을 기본행연산을 사용하여 기약행사다리꼴 형태로 변환하여 해를 구하는 과정
##### - 기약행사다리꼴(Reduced Row Echelon Form) : 선행원소가 1이고 선행원소를 제외한 모든 나머지 원소가 0인 행사다리꼴
##### - 기본행 연산 : 
######  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    1. 두 행의 교환
######  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    2. 행의 상수배
######  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    3. 행을 상수배하여 다른 행에 덧셈
######  
###### *가우스 소거법 : 연립선형방정식을 행사다리꼴(Row Echelon Form) 형태로 변환하는 방법
#### 
##### 코드 설명 : 
###### 가우스-조르당 소거법(https://gyeo-ri.tistory.com/35)

In [2]:
#np.array는 행렬의 상수배 연산 가능 / 파이썬 리스트는 불가능
import numpy as np
import random

#### +) 기약행사다리꼴의 특성
#### 기약행사다리꼴(를 제외한 x를 포현하는 정방행렬)은 항상 0 행을 포함하거나 단위행렬이다.
##### 1. 0행을 포함하는 경우
##### 2. 0행으로 포함하지 않는 경우 -> 선행원소 1을 제외한 모든 같은 행 원소가 0이므로 단위행렬
##### -> 결국 기약행사다리꼴에서 가역행렬은 단위행렬 뿐임(0행을 포함하면 비가역행렬)
##### 행렬 A가 가역행렬이라면 A의 기약행사다리꼴은 단위행렬 I이다.

### 함수 정의
##### random_matrix(rows, cols, max_no=20)
###### - (rows)x(cols) 크기의 랜덤 행렬을 생성
###### - 형렬의 값은 0~20 사이의 정수 -> 부동소수점(float) 형태로 변환
##### 
##### gauss_jordan_elimination(matrix):
###### - 생성된 행렬을 입력하여 가우스-조르당 소거법 수행 후 행렬을 반환
###### - 중간 과정을 print() 함수로 표현

In [3]:
#랜덤 행렬 생성(1~20 사이의 정수)
def random_matrix(rows,cols, max_no=20):
    row_list=[]
    for r in range(rows):
        col_list=[]
        for c in range(cols):
            col_list.append(float(random.randint(0,max_no))) #float형으로 변환함
        row_list.append(col_list)
        
    return np.array(row_list) #넘파이 배열 형태로 변환

def gauss_jordan_elimination(matrix):
    print("가우스-조르당 소거법 예시 \n")
    
    #행렬의 가로 세로 
    mcol = len(matrix[0])
    mrow = len(matrix)
    

    print("최초상태")
    print(matrix, "\n")
    
    
    
    #입력 행렬의 1차 검증 : 값이 모두 0인 열이 있는지 -> 변수의 값을 구할 수 없음
    idx = 0
    for c in range(mcol): #열
        for r in range(mrow): #행
            idx += matrix[r][c]

        if idx == 0: #첫 열이 모두 0
            print(c+1,"열 의 값이 모두 0입니다.")
            return 
            
    #2차 검증 : 행/열의 갯수
        if mrow != mcol - 1: #변수의 갯수(결괏값을 제외한 열의 갯수)와 행의 갯수가 일치하여야 함
            print("해가 무수히 많거나 없습니다.")
            return 

    #1. 가우스 소거법 : Leading 1(선행원소 1)을 찾기 위한 알고리즘
    row_count = 0 #연산 중인 열을 지시
    for col_count in range(mcol-1): #선행 원소 아래의 값(열 하단)이 0이 될때까지 반복 수행
        comp_num = np.inf # 비교할 숫자의 기본값을 무한대로 지정(보다 작은 수)
        
        
        # 첫 열이 1이거나, 0이 아닌 수 중 가장 작은 행을 추출
        for i in range(row_count,mrow):
            if (0 < abs(matrix[i][col_count])) & (abs(matrix[i][col_count]) < abs(comp_num)) : 
                comp_num = matrix[i][col_count] #절댓값이 가장 작은 첫 행의 값

                first_row = i #첫 행으로 사용할 행
                if matrix[i][0] == 1: #1을 찾은 경우 
                    break


        matrix[first_row]=matrix[first_row]/comp_num  #첫 행의 첫 열을 1로 변환
        print(first_row+1,"행이", row_count+1,"행과 교환")
        matrix[first_row], matrix[row_count] = matrix[row_count].copy(), matrix[first_row].copy() #대상 인덱스와 첫 행을 교환


        #상수배 후 덧셈연산
        for j in range(row_count+1,mrow):
            if matrix[j][col_count] != 0:
                con_no = matrix[j][col_count]
                matrix[j] = matrix[j] - con_no * matrix[row_count]

            
        #이미 Leading 1을 찾은 행을 연산에서 제외
        row_count += 1
        print(matrix, "\n")

        
    # 2. Back Substitution(가우스-조르당 소거법) : 기약행사다리꼴 형태로 변환
    for col in range(mcol-2,0,-1):
        for row in range(col-1,-1,-1): #col/row를 파이썬 인덱스에 맞게 적용
            const = matrix[row][col] * -1 #constraint
            print(col+1,"행을",const, "만큼 상수배하여", row+1, "행의", col+1,"열을 소거") #
            matrix[row] += const * matrix[col]
            
            print(matrix, "\n")
    
    print("방정식의 해는")
    print(matrix[:,-1])
    return  # matrix <- 기약사다리꼴 형태를 반환

In [4]:
matrix=random_matrix(3,4)
gauss_jordan_elimination(matrix)

가우스-조르당 소거법 예시 

최초상태
[[ 6.  9.  3. 17.]
 [19.  1.  7.  9.]
 [10. 12.  1.  6.]] 

1 행이 1 행과 교환
[[  1.           1.5          0.5          2.83333333]
 [  0.         -27.5         -2.5        -44.83333333]
 [  0.          -3.          -4.         -22.33333333]] 

3 행이 2 행과 교환
[[  1.           1.5          0.5          2.83333333]
 [ -0.           1.           1.33333333   7.44444444]
 [  0.           0.          34.16666667 159.88888889]] 

3 행이 3 행과 교환
[[ 1.          1.5         0.5         2.83333333]
 [-0.          1.          1.33333333  7.44444444]
 [ 0.          0.          1.          4.6796748 ]] 

3 행을 -1.3333333333333333 만큼 상수배하여 2 행의 3 열을 소거
[[ 1.          1.5         0.5         2.83333333]
 [-0.          1.          0.          1.20487805]
 [ 0.          0.          1.          4.6796748 ]] 

3 행을 -0.5 만큼 상수배하여 1 행의 3 열을 소거
[[ 1.          1.5         0.          0.49349593]
 [-0.          1.          0.          1.20487805]
 [ 0.          0.          1.          4.6796748 ]

In [5]:
#### 블로그 예시(https://gyeo-ri.tistory.com/35)의 구현

In [6]:
matrix=np.array([[2.,2.,1.,11.],[2.,1.,3.,11.],[1.,2.,3.,10.]])
gauss_jordan_elimination(matrix)

가우스-조르당 소거법 예시 

최초상태
[[ 2.  2.  1. 11.]
 [ 2.  1.  3. 11.]
 [ 1.  2.  3. 10.]] 

3 행이 1 행과 교환
[[ 1.  2.  3. 10.]
 [ 0. -3. -3. -9.]
 [ 0. -2. -5. -9.]] 

3 행이 2 행과 교환
[[ 1.   2.   3.  10. ]
 [-0.   1.   2.5  4.5]
 [ 0.   0.   4.5  4.5]] 

3 행이 3 행과 교환
[[ 1.   2.   3.  10. ]
 [-0.   1.   2.5  4.5]
 [ 0.   0.   1.   1. ]] 

3 행을 -2.5 만큼 상수배하여 2 행의 3 열을 소거
[[ 1.  2.  3. 10.]
 [-0.  1.  0.  2.]
 [ 0.  0.  1.  1.]] 

3 행을 -3.0 만큼 상수배하여 1 행의 3 열을 소거
[[ 1.  2.  0.  7.]
 [-0.  1.  0.  2.]
 [ 0.  0.  1.  1.]] 

2 행을 -2.0 만큼 상수배하여 1 행의 2 열을 소거
[[ 1.  0.  0.  3.]
 [-0.  1.  0.  2.]
 [ 0.  0.  1.  1.]] 

방정식의 해는
[3. 2. 1.]
