###### 겨리 - 2021/01/14
### **역행렬과 수반행렬**
#### 역행렬의 일반적인 도출 방법과 수반행렬을 이용한 방법

##### 코드 설명
###### https://gyeo-ri.com/61


In [8]:
import random
import numpy as np

#### 1. 행렬식과 수반행렬(adjoint matrix)
##### 행렬식을 사용하면 행렬의 가역성을 판별할 수 있다(det(A) == 0이면 행렬 A는 비가역행렬)
#### 
#### 수반행렬 : 행렬의 각 원소에 대응하는 여인수들의 행렬의 전치
##### 행렬식을 구하는 알고리즘 사용(det_gauss)
#### 
###### 행렬식 구현 링크
###### https://github.com/gyeo-ri/studies/blob/master/mathmatics/linear_algebra/3.%ED%96%89%EB%A0%AC%EC%8B%9D.ipynb

In [20]:
def adjoint_matrix(matrix_input):
    matrix=matrix_input.copy()
    dim = len(matrix)
    adj = np.zeros((dim,dim)) #수반행렬을 담을 공간
    

    for row in range(dim):
        for col in range(dim): #행렬의 모든 원소를 반복
            
            #해당 원소가 속한 행/열 제거
            partial = np.delete(matrix,row,axis=0)
            partial = np.delete(partial,col,axis=1)
            
            C = det_gauss(partial) *(-1)**(row+col) #단일함수일 경우 행렬식 알고리즘을 그대로 구현
            
            adj[col][row] = C #전치행렬이므로 행과 열을 반대로하여 adj에 삽입
            
    
    return adj

In [21]:
adj_A=adjoint_matrix(A)

In [ ]:
#### 행렬 A와 A의 수반행렬 adj(A)의 행렬곱을 전개하면, 

In [30]:
print("행렬 A는")
print(A)
print()
print("A의 행렬식은(det_gauss 함수 사용)")
print(det_gauss(A))
print()
print("A의 수반행렬은")
print(adj_A)
print()
print("A와 수반행렬 adj(A)의 곱은")
print(np.around(np.dot(A,adj_A))) # A와 adj(A)의 곱은 대각원소가 모두 행렬식인 대각행렬

행렬 A는
[[ 6. 14. 17. 15.]
 [19.  2.  9.  7.]
 [ 4. 13. 19.  6.]
 [ 7. 17. 20.  9.]]

A의 행렬식은(det_gauss 함수 사용)
9810.0

A의 수반행렬은
[[ -474.   486.  -804.   948.]
 [ -652.  -387. -2327.  2939.]
 [  136.   171.  2321. -1907.]
 [ 1298.   -27.  -137.  -961.]]

A와 수반행렬 adj(A)의 곱은
[[9810.   -0.   -0.    0.]
 [   0. 9810.   -0.    0.]
 [   0.   -0. 9810.    0.]
 [   0.   -0.   -0. 9810.]]


#### 2. 역행렬(Inverse Matrix)
##### A의 역행렬 A^(-1)은 A와 곱했을 때 차수가 같은 단위행렬(I)이 출력되는 행렬이다. 
##### 각각의 행렬에 대해 역행렬은 없거나(비가역행렬) 유일하다.
###### 참고 : 행렬의 연산 관련 알고리즘 구현
###### https://github.com/gyeo-ri/studies/blob/master/mathmatics/linear_algebra/2.%ED%96%89%EB%A0%AC%EC%9D%98%20%EC%97%B0%EC%82%B0.ipynb
#### 
##### 이전 노트에서 정의한 가우스-조르당 소거법 및 역행렬 알고리즘 사용

In [6]:
def inverse_matrix(matrix):
    dim = len(A)
    queue=[] #확장행렬의 원소나열규칙을 사전에 큐에 저장해두고 하나씩 꺼냄(FIFO)
    for i in range(dim):
        num = i
        for j in range(dim):
            queue.append(num)
            num +=dim
    queue*= dim**2 # n차원 행렬에서 생성되는 확장행렬의 행은 n^2개이며, 각 행마다 n개의 변수가 있으므로 규칙을 확장

    #확장행렬을 생성하고 초깃값을 0으로 지정
    zero_array = np.zeros((dim**2,dim**2+1))


    for row_no in range(dim**2): #결과 행렬의 행 수만큼 반복
        temp_row = A[row_no//dim]
        for j in range(dim):
            idx = queue.pop(0) 
            zero_array[row_no,idx] = temp_row[j] #i행의 idx열에 대입

        if row_no%(dim+1) == 0:  #결괏값인 단위행렬을 연립방정식의 마지막 열에 구현
            zero_array[row_no, -1] = 1
            
    #사전 정의된 가우스-조르당 소거법 함수가 필요
    echelon_form=gauss_jordan_elimination(zero_array)
    elements=np.array(echelon_form[:,-1])
    inverse_matrix=elements.reshape(dim,-1)
    return inverse_matrix

In [9]:
A=random_matrix(4,4)
A2=A.copy()
A_inv = inverse_matrix(A)

In [39]:
print("행렬 A")
print(A)
print()
print("A의 역행렬(소수 셋째자리까지 반올림)")
print(np.around(A_inv,3))
print()
print("행렬과 역행렬의 곱")
print(np.around(np.dot(A,A_inv),3))

행렬 A
[[ 6. 14. 17. 15.]
 [19.  2.  9.  7.]
 [ 4. 13. 19.  6.]
 [ 7. 17. 20.  9.]]

A의 역행렬(소수 셋째자리까지 반올림)
[[-0.048  0.05  -0.082  0.097]
 [-0.066 -0.039 -0.237  0.3  ]
 [ 0.014  0.017  0.237 -0.194]
 [ 0.132 -0.003 -0.014 -0.098]]

행렬과 역행렬의 곱
[[ 1.  0. -0.  0.]
 [-0.  1.  0. -0.]
 [ 0.  0.  1.  0.]
 [ 0.  0. -0.  1.]]


#### 넘파이 모듈로 역행렬 구하기

In [38]:
np.around(np.linalg.inv(A),3)

array([[-0.048,  0.05 , -0.082,  0.097],
       [-0.066, -0.039, -0.237,  0.3  ],
       [ 0.014,  0.017,  0.237, -0.194],
       [ 0.132, -0.003, -0.014, -0.098]])

# 
# 
# 
# 
# 
#### 다른 노트에서 정의한 함수

In [19]:
#랜덤 행렬 생성(1~20 사이의 정수)
def random_matrix(rows,cols, max_no=20):
    row_list=[]
    for r in range(rows):
        col_list=[]
        for c in range(cols):
            col_list.append(float(random.randint(1,max_no))) #float형으로 변환함
        row_list.append(col_list)
        
    return np.array(row_list) #넘파이 배열 형태로 변환

def gauss_jordan_elimination(matrix):
    
    #행렬의 가로 세로 
    mcol = len(matrix[0])
    mrow = len(matrix)
    row_count = 0 #연산 중인 열을 지시

    
    
    #입력 행렬의 1차 검증 : 값이 모두 0인 열이 있는지 -> 변수의 값을 구할 수 없음
    idx = 0
    for c in range(mcol): #열
        for r in range(mrow): #행
            idx += matrix[r][c]

        if idx == 0: #첫 열이 모두 0
            print(c+1,"열 의 값이 모두 0입니다.")
            return 
            
    #2차 검증 : 행/열의 갯수
        if mrow != mcol - 1: #변수의 갯수(결괏값을 제외한 열의 갯수)와 행의 갯수가 일치하여야 함
            print("해가 무수히 많거나 없습니다.")
            return 

        
    #1. 가우스 소거법 : Leading 1(선행원소 1)을 찾기 위한 알고리즘
    for col_count in range(mcol-1): #선행 원소 아래의 값(열 하단)이 0이 될때까지 반복 수행
        comp_num = np.inf # 비교할 숫자의 기본값을 무한대로 지정(보다 작은 수)
        
        
        # 첫 열이 1이거나, 0이 아닌 수 중 가장 작은 행을 추출
        for i in range(row_count,mrow):
            if (0 < abs(matrix[i][col_count])) & (abs(matrix[i][col_count]) < abs(comp_num)) : 
                comp_num = matrix[i][col_count] #절댓값이 가장 작은 첫 행의 값

                first_row = i #첫 행으로 사용할 행
                if matrix[i][0] == 1: #1을 찾은 경우 
                    break


        matrix[first_row]=matrix[first_row]/comp_num  #첫 행의 첫 열을 1로 변환
        matrix[first_row], matrix[row_count] = matrix[row_count].copy(), matrix[first_row].copy() #대상 인덱스와 첫 행을 교환


        #선행원소를 1로 만드는 과정
        for j in range(row_count+1,mrow):
            if matrix[j][col_count] != 0:
                con_no = matrix[j][col_count]
                matrix[j] = matrix[j] - con_no * matrix[row_count]

            
        #이미 Leading 1을 찾은 행을 연산에서 제외
        row_count += 1

        
    # 2. Back Substitution(가우스-조르당 소거법) : 기약사다리꼴 형태로 변환
    for col in range(mcol-2,0,-1):
        for row in range(col-1,-1,-1): #col/row를 파이썬 인덱스에 맞게 적용
            const = matrix[row][col] * -1 #constraint
            matrix[row] += const * matrix[col]
            
    return  matrix


def det_gauss(matrix_input):
    matrix=matrix_input.copy() #기존 배열을 보존하기 위해
    dim = len(matrix)
    det = 1 #행사다리꼴의 행렬식은 1

    row_count = 0
    for col_count in range(dim): #선행 원소 아래의 값(열 하단)이 0이 될때까지 반복 수행
        comp_num = np.inf # 비교할 숫자의 기본값을 무한대로 지정(보다 작은 수)
        
        
        # 첫 열이 1이거나, 0이 아닌 수 중 가장 작은 행을 추출
        for i in range(row_count,dim):
            if (0 < abs(matrix[i][col_count])) & (abs(matrix[i][col_count]) < abs(comp_num)) : 
                comp_num = matrix[i][col_count] #절댓값이 가장 작은 첫 행의 값

                first_row = i #첫 행으로 사용할 행
                if matrix[i][0] == 1: #1을 찾은 경우 
                    break
                    
            

        
        matrix[first_row]=matrix[first_row]/comp_num  #첫 행의 첫 열을 1로 변환
        #print(round(comp_num,3), "만큼 상수배 적용")
        det *= comp_num #상수배 만큼 적용
        
        if first_row != row_count:
            det *= -1
            #print(first_row+1,"행이", row_count+1,"행과 교환")
            matrix[first_row], matrix[row_count] = matrix[row_count].copy(), matrix[first_row].copy() #대상 인덱스와 첫 행을 교환
        
        #first_row가 첫 행을 가리키지 않으면 첫 행과 다른 행이 1회 행교환되었으므로 부호가 음수가 됨

            
        #상수배 후 덧셈연산(행렬식에 영향을 주지 않음)
        for j in range(row_count+1,dim):
            if matrix[j][col_count] != 0:
                con_no = matrix[j][col_count]
                matrix[j] = matrix[j] - con_no * matrix[row_count]
                
        row_count += 1

        
    return det